services:
  jira-estimation-app:
    # Use pre-built image by default (fastest)
    # image: shock3udt/jira-estimation:latest

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py
    volumes:
      - ./database:/app/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  database:
    driver: local