services:
  jira-estimation-app:
    # Use pre-built image by default (fastest)
    # image: shock3udt/jira-estimation:latest

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py
      # Email Configuration - Add these to your .env file
      # IMPORTANT: MAIL_SENDER must be set to avoid sender/recipient issues
      # - MAIL_SERVER=mail.vas-hosting.cz
      # - MAIL_PORT=465
      # - MAIL_USE_TLS=false
      # - MAIL_USE_SSL=true
      # - MAIL_USERNAME=no-reply@mitruk.eu
      # - MAIL_SENDER=no-reply@mitruk.eu  # REQUIRED: Must be different from recipient emails
      # - MAIL_PASSWORD=your_email_password
      # - APP_BASE_URL=http://localhost:8080
    volumes:
      - ./database:/app/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - .env
volumes:
  database:
    driver: local